name: success_coaching_centre
description: "A complete Coaching Institute Management app for NVS, Sainik School, and CHS prep."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # सुंदर आइकन्स के लिए
  cupertino_icons: ^1.0.5

  # फायरबेस के टूल्स (जो हमने अभी जोड़े)
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/app_icon.png"
  
